version: "3"

services:
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web interface
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
